config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :shifts, only: [:index, :edit, :update, :new, :create, :destroy]
  resources :workers, only: [:index, :edit, :update, :new, :create]

  root to: 'shifts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shift.rb
class Shift < ApplicationRecord
    belongs_to :worker
    validates :worker_id, :start_date, presence: true

    def start_time
        self.start_date
    end
end

app/models/worker.rb
class Worker < ApplicationRecord
    STATUSES = %w(medic intern interim)
    has_many :shifts

    validates :first_name, :last_name, presence: true
    validates :status, inclusion: { in: STATUSES, allow_nil: false }

    def nb_shifts_this_month
        current_month = Date.today.mon
        nb_shifts = Shift.count { |shift| shift.worker_id == self.id && shift.start_date.mon == current_month }
    end

    def nb_shifts
        current_month = Date.today.mon
        nb_shifts = Shift.count { |shift| shift.worker_id == self.id }
    end

    def name
        "#{self.first_name} #{self.last_name}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_shift, only: [:show, :edit, :update, :destroy]

  def index
    @shifts = Shift.all
    @shifts_date = @shifts.map { |shift| shift.start_date }
    return @shifts, @shifts_date
  end

  def new
    if (params[:worker_id])
      @shift = Shift.new()
      @shift.worker_id = params[:worker_id]
    elsif (params[:shift])
      @shift = Shift.new(shift_params)
    else
      @shift = Shift.new
    end
  end

  def edit
  end

  def create
    @shift = Shift.new(shift_params)
    @shifts = Shift.where(start_date: @shift.start_date)

    respond_to do |format|
      if @shifts.count > 0
        flash[:alert] = "Date already assigned, please remove the shift before adding a new one"
        format.html { redirect_to shifts_url }
      elsif @shift.save
        format.html { redirect_to shifts_url, notice: 'Shift was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @shift.update(shift_params)
        format.html { redirect_to shifts_url, notice: 'Shift was successfully updated.' }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @shift.destroy
    respond_to do |format|
      format.html { redirect_to shifts_url, notice: 'Shift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_shift
      @shift = Shift.find(params[:id])
    end

    def shift_params
      params.require(:shift).permit(:start_date, :worker_id)
    end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:edit, :update, :destroy]
  serialization_scope :view_content

  def index
    @workers = Worker.all

    respond_to do |format|
      format.json { render json: @workers, each_serializer: WorkerSerializer }
      format.html
    end
  end

  def new
    @worker = Worker.new
  end

  def edit
  end

  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to workers_url, notice: 'Worker was successfully created.' }
      else
        flash[:alert] = "there is a problem"
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to workers_url, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_worker
      @worker = Worker.find(params[:id])
    end

    def worker_params
      params.require(:worker).permit(:first_name, :last_name, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Esante</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.0rc1/angular-route.min.js"></script>
    <script src="https://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-2.5.0.js"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="<%= params[:controller] %> <%= params[:action] %>">

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="height-page">
      <%= yield %>
    </div>

    <footer>
      <%= render 'shared/footer' %>
    </footer>

    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
 <div class="alert alert-info alert-dismissible" role="alert">
   <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
   <%= notice %>
 </div>
<% end %>
<% if alert %>
 <div class="alert alert-warning alert-dismissible" role="alert">
   <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
   <%= alert %>
 </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer hidden-xs hidden-sm">
  <div class="container">

    <div class="row">
      <div class="col-xs-12 col-sm-6">

      </div>

      <div class="col-xs-12 col-sm-6">
        <div class="text-footer-right">
          <p>Coded with love</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-esante navbar-esante-fixed">
  <div class="navbar-center">
    <div class="link-button">
      <%= link_to 'PLANNING', shifts_path, class: "link-navbar" %>
    </div>
    <div class="link-button">
      <%= link_to 'WORKERS', workers_path, class: 'link-navbar' %>
    </div>

  </div>
</div>

app/views/shifts/_form.html.erb
<div class="form">
    <%= simple_form_for(@shift) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.select :worker_id, Worker.all.map { |w| [w.name, w.id] }, {}, { multiple:false, class: 'selectize' } %>
        <%= f.input :start_date, as: :date, label: "Shift date:", order: [:day, :month, :year] %>
      </div>

      <div class="form-actions">
        <%= link_to 'cancel', shifts_path, class: 'btn btn-default button-esante-default' %>
        <%= f.button :submit, { value: 'save', class: 'btn button-esante' } %>
      </div>
    <% end %>
</div>

app/views/shifts/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
            <div class="form-title">
                <h1>Editing Shift</h1>

                <%= render 'form', shift: @shift %>

            </div>
        </div>
    </div>
</div>

app/views/shifts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="calendar-esante">
        <%= link_to new_shift_path do %>
          <%= icon('plus', class: 'add-shift-big') %>
        <% end %>

        <%= month_calendar events: @shifts do |date, shifts| %>

          <%= date.strftime("%d") %>

          <% if !@shifts_date.include?(date) %>
            <%= link_to new_shift_path(:shift => { :start_date => date }) do %>
              <div class="add-shift"></div>
            <% end %>
          <% end %>



          <% shifts.each do |shift| %>
              <div id='shift-event' class='shift-event shift-event-<%= shift.id %>' data-id='<%= shift.id %>'>
                <%= shift.worker.first_name %> <%= shift.worker.last_name %>

                <%= render 'workers/dialog', shift: shift %>
              </div>
          <% end %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/shifts/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
            <div class="form-title">
                <h1>Add a shift</h1>
            </div>
            <%= render 'form', shift: @shift %>
        </div>
    </div>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/workers/_dialog.html.erb
<div class="dialog-container dialog-container-<%= shift.id %> hide">
  <div class='dialog-title'>
    <h1><%= shift.start_date.strftime("%B %d, %y") %></h1>
    <%= icon('times', class: 'close-icon') %>

    <%= link_to shift, method: :delete do %>
      <%= icon('trash', class: 'delete-icon') %>
    <% end %>

    <%= link_to edit_shift_path(shift) do %>
        <%= icon('pencil', class: 'edit-shift') %>
    <% end%>
  </div>
  <div class="dialog-content">
    <p>Firstname: <span><%= shift.worker.first_name %></span></p>
    <p>Lastname: <span><%= shift.worker.last_name %></span></p>
    <p>Status: <span><%= shift.worker.status %></span></p>
  </div>
</div>

app/views/workers/_form.html.erb
<div class="form">
  <%= simple_form_for(@worker) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :first_name %>
      <%= f.input :last_name %>
      <%= f.input :status, collection: Worker::STATUSES, label: false, prompt: "select a status" %>
    </div>

    <div class="form-actions">
      <%= link_to 'Back', workers_path, class: 'btn button-esante-default' %>
      <%= f.button :submit, { class: 'button-esante btn-sm' } %>
    </div>
  <% end %>
</div>

app/views/workers/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
            <div class="form-title">
                <h1>Edit a worker</h1>
            </div>
            <%= render 'form', worker: @worker %>
        </div>
    </div>
</div>

app/views/workers/index.html.erb
  <div class="container" ng-app="eSante">
    <div ng-controller="WorkerCtrl">
      <div class="worker-index">
        <div class="row">
          <div class="col-xs-12">
            <div class="table-worker-header">
              <input type="text" class="search-worker" data-ng-model="table" placeholder="search for anything about worker" />
              <a class='button-esante btn-sm' href="workers/new">Add a worker</a>
            </div>
          </div>
          <div class="col-xs-12">
            <table>
              <tr class='worker-table-columns-title'>
                <th class="text-center">ID</th>
                <th class="text-center">Name</th>
                <th class="text-center">Status</th>
                <th class="text-center">Shifts number this month </th>
                <th class="text-center">Total shifts number</th>
                <th class="text-center">Actions</th>
              </tr>
              <tr class='worker-table-content' ng-repeat="worker in final_workers | filter:table">
                <td class="text-center">{{worker.id}}</td>
                <td class="text-center">{{worker.name}}</td>
                <td class="text-center">{{worker.status}}</td>
                <td class="text-center">{{worker.nb_shifts_this_month}}</td>
                <td class="text-center">{{worker.nb_shifts}}</td>
                <td class='actions-workers'>
                  <a href="/workers/{{worker.id}}//edit">
                    <%= icon('pencil', class: 'edit-worker') %>
                  </a>
                  <a href="shifts/new?worker_id={{worker.id}}">
                    <%= icon('plus', class: 'add-worker-shift') %>
                  </a>
                </td>
              </tr>
            </table>
            <div uib-pagination previous-text="" next-text="" total-items='workers.length' ng-model='currentPage' ng-change="pageChanged()" items-per-page='numPerPage' ng-change="pageChanged()" boundary-links ="true"></div>
          </div>
        </div>
      </div>



    </div>
</div>

app/views/workers/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
            <div class="form-title">
                <h1>Add a worker</h1>
            </div>
            <%= render 'form', worker: @worker %>
        </div>
    </div>
</div>